#!/usr/bin/env python3
"""Generate kernel/sec_vendor_crcs.h from a set of Samsung vendor .ko files.

Each vendor .ko has a `__versions` section containing one
`struct modversion_info` per imported symbol:

    struct modversion_info {
        unsigned long crc;          /* 8 bytes on arm64    */
        char name[64 - sizeof(long)]; /* 56 bytes NUL-padded */
    };

We harvest every (symbol_name, crc) pair from the supplied modules,
deduplicate, sort by name, and emit a static C array that
`kernel/module.c::check_version()` consults as a fallback when its own
genksyms-computed CRC disagrees with the module's expected CRC.

Usage:
    sec_extract_vendor_crcs.py <module.ko> [module.ko ...]

The header is written to stdout. Redirect into kernel/sec_vendor_crcs.h.
"""
import os
import struct
import subprocess
import sys
import tempfile

ENTRY_SIZE = 64
NAME_LEN = ENTRY_SIZE - 8  # 56 bytes


def extract_versions(ko_path):
    """Run objcopy to dump the __versions section as raw bytes."""
    with tempfile.NamedTemporaryFile(delete=False) as tmp:
        tmp_path = tmp.name
    try:
        subprocess.run(
            ["aarch64-linux-gnu-objcopy", "-O", "binary",
             "--only-section=__versions", ko_path, tmp_path],
            check=True,
        )
        with open(tmp_path, "rb") as f:
            return f.read()
    finally:
        os.unlink(tmp_path)


def parse_entries(blob):
    """Yield (name, crc) tuples from a __versions blob."""
    for off in range(0, len(blob), ENTRY_SIZE):
        chunk = blob[off:off + ENTRY_SIZE]
        if len(chunk) < ENTRY_SIZE:
            return
        crc = struct.unpack_from("<Q", chunk, 0)[0]
        name = chunk[8:].split(b"\x00", 1)[0].decode("ascii", errors="replace")
        if not name:
            continue
        if crc >> 32:
            sys.stderr.write(
                f"warning: CRC for {name} has high bits set ({crc:#x})\n")
        yield name, crc & 0xFFFFFFFF


def main(argv):
    if len(argv) < 2:
        sys.stderr.write(__doc__)
        return 1

    pairs = {}  # name -> crc
    for ko in argv[1:]:
        for name, crc in parse_entries(extract_versions(ko)):
            existing = pairs.get(name)
            if existing is None:
                pairs[name] = crc
            elif existing != crc:
                sys.stderr.write(
                    f"error: conflicting CRCs for {name}: "
                    f"{existing:#010x} vs {crc:#010x} (from {ko}); "
                    f"the input modules are not all from the same firmware\n")
                return 2

    out = sys.stdout
    out.write("/*\n")
    out.write(" * Auto-generated by scripts/sec_extract_vendor_crcs.py.\n")
    out.write(" * DO NOT EDIT BY HAND - regenerate from the matching\n")
    out.write(" * Samsung vendor .ko set if it goes out of date.\n")
    out.write(" *\n")
    out.write(" * Source firmware: X205XXS6DYG6\n")
    out.write(" * vermagic:        4.14.199-29056031-abX205XXS6DYG6\n")
    out.write(" *\n")
    out.write(" * Whitelist of (symbol, CRC) pairs that LineageOS's\n")
    out.write(" * check_version() will accept as a fallback when its own\n")
    out.write(" * genksyms-computed CRC disagrees with what the vendor\n")
    out.write(" * module expects. Real ABI breaks still get rejected,\n")
    out.write(" * because the module's CRC has to actually match the\n")
    out.write(" * value the X205 stock kernel had for that symbol.\n")
    out.write(" */\n")
    out.write("#ifndef _KERNEL_SEC_VENDOR_CRCS_H\n")
    out.write("#define _KERNEL_SEC_VENDOR_CRCS_H\n")
    out.write("\n")
    out.write("#include <linux/types.h>\n")
    out.write("\n")
    out.write("struct sec_vendor_crc {\n")
    out.write("\tconst char *name;\n")
    out.write("\tu32 crc;\n")
    out.write("};\n")
    out.write("\n")
    out.write("/* Sorted by name so check_version() can binary-search. */\n")
    out.write("static const struct sec_vendor_crc sec_vendor_crcs[] = {\n")
    for name in sorted(pairs):
        out.write(f"\t{{ \"{name}\", 0x{pairs[name]:08x} }},\n")
    out.write("};\n")
    out.write("\n")
    out.write("#define SEC_VENDOR_CRCS_COUNT ARRAY_SIZE(sec_vendor_crcs)\n")
    out.write("\n")
    out.write("#endif /* _KERNEL_SEC_VENDOR_CRCS_H */\n")

    sys.stderr.write(
        f"sec_extract_vendor_crcs: emitted {len(pairs)} unique symbols\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
