# SPDX-License-Identifier: GPL-2.0
#
# Tab A8 (gta8) downstream-WLAN kprobes.
# See Kconfig for what each module does.
#

obj-$(CONFIG_GTA8_SPRDWL_HOLDTIME)  += sprdwl_holdtime.o
obj-$(CONFIG_GTA8_SPRDWL_RX_KPROBE) += sprdwl_rx_kprobe.o

ccflags-y := -Wno-unused-function
